# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XAO-Commerce
version:      1.02
version_from: Commerce.pm
installdirs:  site
requires:
    Test::Unit:                    0.14
    XAO::Base:                     1.04
    XAO::DO::Catalogs:             1.01
    XAO::FS:                       1.04
    XAO::Web:                      1.04

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
